version: '3.3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
        MYSQL_DATABASE: 'dbassemblyProject'
        MYSQL_USER: 'user'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '9005:3306'
    expose:
      - '9005'
    volumes:
      - my-db:/var/lib/mysql

volumes:
  my-db:

